### ISSUE TITLE
Printer Path Sensor is no correctly registered

### ISSUE THREAD

**Issue by IcarianOM** [PyramidTechnologies/PTI.Reliance.Tools#12] opened 2020-03-04 23:44 UTC
**Describe the bug**
The arm sensor of the printer is not read by  

Status status = printer.GetStatus();

**Screenshots**

Data with paper on the sensor:
![image](https://user-images.githubusercontent.com/57366931/75933351-68a7cf00-5e3f-11ea-8598-f1691dde97c9.png)
Data without paper on the sensor:
![image](https://user-images.githubusercontent.com/57366931/75933379-78bfae80-5e3f-11ea-8da2-1e00f427713f.png)

**Environment**
 - Library version: 1.2.1
 - Installation method NuGet
 - OS: Windows x86
 - Version 7
 - Framework [ .NET 4.7.1]

**Additional context**
```
           try
            {
                using (var printer = new ReliancePrinter())
                {
                    var ping = printer.Ping();
                    if (ping == ReturnCodes.Okay)
                    {
                        GlobalVariables.thermalPrinterStatus = "1";
                    }
                    else
                    {
                        GlobalVariables.thermalPrinterStatus = "0";
                    }
                    var revlev = printer.GetFirmwareRevision();
                    Status status = printer.GetStatus();
                    Console.WriteLine("PaperRaw: " + status.PaperRaw); 
                    Console.WriteLine("PathRaw: " + status.PathRaw);
                    
                    Console.WriteLine("Printer status:\n{0}", status);
            }
            catch (Exception E)
            {
                Console.WriteLine("CheckTermalPrinterStatus Exception: " + E.Message);
            }


```

**Comment by corytodd** [comment] 2020-03-05 00:01
Can you confirm which sensor you are testing? The title says path sensor but the body mentions the arm sensor.

You can use our real time monitor to confirm which sensors you are covering using [WinRelMon](https://pyramidacceptors.com/apps/WinRelMon.exe). Let me know which sensor(s) are not reporting correctly and we can get to the bottom of this.

**Comment by IcarianOM** [comment] 2020-03-05 17:11
i ran the app and nothing changed once i put the paper on the arm and remove it.
the firmware version  of the printer is 1.14.134

**Comment by corytodd** [comment] 2020-03-05 17:54
Okay thanks for confirming that we're talking about the paper arm sensor. Let's start by getting that firmware updated. Please send an email to support@pyramidacceptors.com and we can send you the latest version and troubleshoot the hardware from there. It sounds like something is wrong with the sensor or sensor harness.

**Comment by IcarianOM** [comment] 2020-03-05 18:06
Thanks. I will try to get the firmware. I think thats the problem, since we are using +20 printers and we cant have a good reading of that sensor.

**Comment by corytodd** [comment] 2020-03-05 21:30
I confirmed with support that you reached out them for the firmware. Since this does not look like an issue with the API I'm going to close this issue.

**Closed by corytodd** 2020-03-05 21:30 UTC
Labels: question
